### ISSUE TITLE
Usability: center on grid select

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#109]
One usability issue I've come across when browsing at high zoom levels is the recentering when selecting a grid square. 

Use case -- Select a grid to see available imagery. Once you find a good image, it's interesting to zoom in to see the preview overlaid on the map. Occasionally a click of the grid causes the grid to be deselected. When reselecting, you are taken to the center of the grid at a high zoom level which causes you to lose your position on the map. 

@ricardomestre @danielfdsilva thoughts on how we could improve this interaction? Remove the centering? Or punt on it until we look at more grid adjustments?

**Comment by danielfdsilva** [comment]
A new grid system was developed.
If this is still a problem reopen
