### ISSUE TITLE
Open in iD not fully functioning

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#111]
Open in iD function does not seem to be fully functioning. It seems that the iD editor does not initialize once you are taken over to openstreetmap.org. The link correctly navigates you over to OSM, but iD does not open with the imagery as the custom base layer. Seeing this in Chrome Version 44.0.2403.125. 

Looking at this view on OAM: http://beta.openaerialmap.org/#/10.790140750321738,124.93652343749999,8/10.790112856939729,124.9365234375/55d1daea2b67227a79b4f4eb

Seems to be using this URL: 
```
http://www.openstreetmap.org/edit#map=8/10.679211111111112/124.81366041666666?editor=id&background=custom%3Ahttp%3A%2F%2Fa.tiles.mapbox.com%2Fv4%2Fopenroads.n6p4np8h%2F%7Bz%7D%2F%7Bx%7D%2F%7By%7D.jpg%3Faccess_token%3Dpk.eyJ1Ijoib3BlbnJvYWRzIiwiYSI6InJ0aUQ2N3MifQ.R3hdFqriZr6kEUr-j_FYpg
```

**Comment by danielfdsilva** [comment]
Turns out it is not really our problem.
https://github.com/openstreetmap/iD/pull/2781
