### ISSUE TITLE
Splash modal loaded linked from sharable URL

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#112]
When using a sharable URL like http://beta.openaerialmap.org/#/10.790140750321738,124.93652343749999,10/10.790112856939729,124.9365234375, landing modal is still loaded on top. 

![](https://api.monosnap.com/rpc/file/download?id=lwdx4JPQXXDJ2deSVHhIHWTp3KSn4i)

@ricardomestre @danielfdsilva Ideas for how we could improve this interaction? It is helpful to have the modal for new users or users looking to find the latest imagery but maybe it's worthwhile to not load this when directly linked?

**Comment by cgiovando** [comment]
Thanks for noting this @smit1678 - agree that splash window should not display with direct links. I would almost skip that entirely and show the main map window directly. By default the map location could be set to the last visited area (tracked by browser cookies?) or to a random area of last uploaded imagery. Similar to how osm.org works?
