### ISSUE TITLE
Incorrect thumbnail placement

### ISSUE THREAD

**Issue by anandthakker** [hotosm/oam-browser#115]
http://beta.openaerialmap.org/#/54.13830552010698,-4.79278564453125,8/54.13662444363425,-4.7900390625/556f7a4bac00a903002fb292

**Comment by anandthakker** [comment]
<img width="920" alt="screen shot 2015-09-02 at 11 46 40 am" src="https://cloud.githubusercontent.com/assets/4974151/9636241/6cf1c68a-5168-11e5-9d1b-5db455fb7823.png">

**Comment by anandthakker** [comment]
This could be a metadata problem or a rendering problem -- not sure which.

**Comment by danielfdsilva** [comment]
This was probably fixed with the new system.
Re-open of the problem persists.
