### ISSUE TITLE
mabox-gl thumbnail loading

### ISSUE THREAD

**Issue by danielfdsilva** [hotosm/oam-browser#118]
Thumbnails are not being loaded.
Mapbox uses canvas to draw the images and it's not possible to load cross domain images without CORS.
This is a problem specially with USGS images.

Talking with @drewbo, he said to have had the same problem for AD and it was solved using a proxy. We could use said proxy for those images but probably we'd still have a problem with other sources.

@anandthakker are the thumbnail sources finite?

We can create our own proxy or talk with @scisco to check if it's possible to extend AD's.

Thoughts?

**Comment by jflasher** [comment]
We could stick the proxy on the Dev Seed nginx as well, or you might just be able to use AD's?

**Comment by smit1678** [comment]
Closing this since GL was not implemented.
