### ISSUE TITLE
Use custom_tms if present

### ISSUE THREAD

**Issue by anandthakker** [hotosm/oam-browser#120]
The OAM Server will be tiling images and adding tms uri's via the catalog's tms endpoint.  It looks like the [logic there](https://github.com/hotosm/oam-catalog/blob/develop/controllers/meta.js#L184-L199) has these going into `custom_tms` rather than `properties.tms`, but here in the browser, we're [only using the latter](https://github.com/hotosm/oam-browser/blob/develop/app/assets/scripts/components/results_item.js#L96-L123).

**Comment by danielfdsilva** [comment]
@anandthakker @smit1678 Fixed but I didn't find any image with a `custom_tms` field. Could you please double check?

**Comment by anandthakker** [comment]
@danielfdsilva I don't believe we have any images that have `custom_tms` yet, because the OAM tiling server has not started interacting w the catalog yet.  @smit1678 is that right?

**Comment by smit1678** [comment]
@anandthakker It's interacting and adding to the /tms endpoint: http://api.openaerialmap.org/tms. Realizing that the above ^ work still won't be grabbing this endpoint. We'll need to hit this new endpoint to search for the available new custom tms.
