### ISSUE TITLE
Browse Latest button loads a selected image

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#121]
From `feature/new-grid-system` branch. 

Browse latest button loads a selected image. @danielfdsilva Do we want to load the latest image or the grid that has the latest image? I think this makes sense as amount of imagery increases and points users directly the latest imagery. Want to confirm that this is the intended interaction. 

![](https://api.monosnap.com/rpc/file/download?id=5Hote7OgUCCeQ9tSbaEPQo4nu2SwZ9)

**Comment by danielfdsilva** [comment]
This was indeed the intended interaction.
Selecting the grid cell can lead the users to error because the images can be old. Not all of them will be "the latest imagery"

**Comment by smit1678** [comment]
@danielfdsilva right, I agree with this approach. let's close this out, I don't think we need to change.
