### ISSUE TITLE
Label for select grid square 

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#123]
From `feature/new-grid-system` branch. 

@danielfdsilva @ricardomestre Do we want add a label to define the grid square? 

![](https://api.monosnap.com/rpc/file/download?id=MI8NoA6F6cBEId9jzKWmyWIfwMzuZE)

**Comment by danielfdsilva** [comment]
You mean a more human readable solution? Or perhaps a generic "Square imagery"?
That's the square quadkey. True that it won't add much for the vast majority of users but for some it might be useful.
