### ISSUE TITLE
Grid size

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#125]
For `feature/new-grid-system` branch. 

@danielfdsilva Really like the grid size at higher zoom levels, but I'm also seeing a little delay occasionally (potentially due to my computer). What does grid size do to the the speed? Would increasing the size slightly increase the snappiness?

**Comment by danielfdsilva** [comment]
The slowness is related to the grid rendering. Computing it and the calculating the intersections is pretty fast but the render takes some time. 
Increasing the grid size would improve performance but it can't just be scaled at random right @anandthakker?

**Comment by anandthakker** [comment]
Right: the grid, like map tiles, has to be scaled by a factor of 4 (or
powers of 4)
