### ISSUE TITLE
Skip splash screen on direct links

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#138]
When users come to OAM from a direct link, the splash screen should be skipped.

**Comment by smit1678** [comment]
This should be working and was implemented in https://github.com/hotosm/oam-browser/issues/112. @danielfdsilva perhaps something was reverted or is a browser issue?

**Comment by danielfdsilva** [comment]
It is working on the current live version. Tested both by @ricardomestre and I

**Comment by danielfdsilva** [comment]
Modal now shows only if you have a url without parameters:
- `http://beta.openaerialmap.org` will show
- `http://beta.openaerialmap.org/#/-80.01411437988281,-0.01991271932569106,10` won't show
