### ISSUE TITLE
Add feedback form

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#140]

**Comment by danielfdsilva** [comment]
TODO:
- [ ] Where to store the data
- [ ] Review form copy
- [ ] Add modal trigger
- [ ] Define subject options

**Comment by smit1678** [comment]
For subject options, thinking: 
  
  - Report a technical issue
  - Let us know what you think
  - Get in touch with OAM team
  - Everything else

@ricardomestre @cgiovando

**Comment by smit1678** [comment]
> Where to store the data

@danielfdsilva to look into it more. 

> Add modal trigger

@DylanMoriarty @ricardomestre where you do think we should put the trigger? We talked about maybe putting it on the map or in the About dropdown?

**Comment by danielfdsilva** [comment]
First version of the modal up on `feature/feedback`.

Data is being stored in a google doc for now.
For the trigger I used the "Contact" button on the dropdown. This needs to be reviewed.

**Comment by DylanMoriarty** [comment]
Tucking it into the "About" dropdown seems fine to me. That dropdown is the current home to the 'contact us' and is the closet thing we have to a sub menu for the site. If we need more sub elements like that for the site, it might be worth revisiting that button and maybe doing something more menu-y.

A Feedback form is tangential enough to _information about this site_ that I think it would do fine living in there.

**Comment by smit1678** [comment]
@danielfdsilva 👍 

@DylanMoriarty Yeah. One follow up question is around reporting map issues. Think putting it in the About dropdown limit the ability to report a issue with the map (like thumbnail broken, or TMS doesn't work)? Or do we just add an extra link within the map area that says something like `Report an issue with the map`.

**Comment by danielfdsilva** [comment]
We could have dedicated buttons in strategic places that would pre-fill the
subject.

**Comment by DylanMoriarty** [comment]
For issues directly associated with the map area, we could add 'Report an issue with the map' to the annotation. (the line that reads ```© Mapbox © OpenStreetMap Improve this map``` could instead say ```© Mapbox © OpenStreetMap | Report an bug with the map. ```).

'Improve the map' goes to a feedback form for MB that just let's someone point out if something is wrong with the OSM layer of the map. I can see that being useful here if someone spots something off, but think it might be confusing if we have both 'Report an issue with the map' & 'Improve map' in the same line, particularly because both would be going to feedback forms.

**Comment by smit1678** [comment]
@DylanMoriarty Agreed on the point about having two report links, we should just have one.
