### ISSUE TITLE
Redesign About modal

### ISSUE THREAD

**Issue by ricardomestre** [hotosm/oam-browser#149]
Incorporate:
- History of OAM (timeline-like)
- Links to elsewhere (Gitter, GitHub, etc)
- ...

**Comment by DylanMoriarty** [comment]
With a landing page we have an opportunity to better highlight these sort of features. I'm a bit torn on whether this opens a modal or just goes straight to a page. For now I think there's enough value in keeping a modal that gives a brief version 'about' the map and then links out to the more fleshed out page.

Something along these lines:

<img width="891" alt="screenshot 2016-06-28 17 15 39" src="https://cloud.githubusercontent.com/assets/9341928/16432642/f893d6ba-3d53-11e6-9ddd-1ebc5b1ee36b.png">

I also feel we should move the 'User Guide' to the menu- I think that's important to have and could be made easier to find if it's there as opposed to tucked away in the modal.

**Comment by smit1678** [comment]
Some of this was implemented by switching from a modal to a link to the /About page. But let's close this and move history, timeline, etc convos into this new ticket about redesigning parts of oam.org: https://github.com/hotosm/openaerialmap.org/issues/24
