### ISSUE TITLE
Zoom to Extent for selected result

### ISSUE THREAD

**Issue by DylanMoriarty** [hotosm/oam-browser#151]
While browsing the imagery, I noticed there isn't a button that just zooms to the selected imagery. I noticed it when I'd selected a larger area in the Philippines and then tried to navigate through the side panel. For some of the higher res images, this could be useful to have.

<img width="1042" alt="screenshot 2016-06-15 15 11 28" src="https://cloud.githubusercontent.com/assets/9341928/16093817/74c4eb64-330b-11e6-8fff-4640b69509ee.png">

**Comment by smit1678** [comment]
@DylanMoriarty Yeah I like that and I think that could be useful.

**Comment by smit1678** [comment]
To bring the convo from #188 and raise this issue up again: 

> When browsing at lower zoom levels and selecting an image, a user is not zoomed in or centered on that image for preview. It could be useful to zoom in and center to enable a quicker preview of the image footprint, thumbnail, and TMS.
>
>This would greatly improve the new TMS work since imagery is not rendered until higher zoom levels. By centering and zooming to an appropriate zoom level for the image, this would improve the experience for viewing the TMS.
