### ISSUE TITLE
OAM Landing Page Wireframe

### ISSUE THREAD

**Issue by DylanMoriarty** [hotosm/oam-browser#154]
@smit1678 @ricardomestre @danielfdsilva @nbumbarger 

We've had a few discussions on what the initial view of OpenAerialMap will look like. The current landing page is quickly clicked through, as is the in browser one.

We want it accomplish:
- Establish what OAM is
- Drive users to places we want them to go (_explore/upload_)
- Highlight other tools made with OAM to give examples of what can be done.
- Show how frequently imagery is updated so that users will want to come back frequently (_view latest imagery_)
- Have a way for experienced users to dive right into the tool

To achieve those goals, I think having a traditional, improved landing page is the route to go.

![desktop](https://cloud.githubusercontent.com/assets/9341928/16277790/5e5730b8-3882-11e6-9557-9213e6ef624a.png)

By having a navigation at the top of the page we are surfacing the options users have, giving them a better sense for what the site is and saving them clicks. 'Community' (could also be called contribute) is a catch all for the tools built off OAM. About would take you to a quick about page and links out to the Github, & OAM Docs.

The current landing page is easy to skip because although it says explicitly what OAM is, it doesn't do so in an effective manner. We can tell more of a story as users scroll down the page. This layout engages them as they scroll, giving them a little bit of information at a time. It also drives them to important areas on the site. 

Nate said that the "View latest imagery" button was pretty popular but as it is now, users can't get back to it because it is in a modal that disappears once closed. If we instead include examples of the latest imagery on the homepage users will always be able to access this information and it will give new users an idea of how frequently the site is updated. This could also make it clear that the imagery isn't just USGS and might help folks understand where OAM efforts are currently located.

Next to show users of what can be done with OAM, we can highlight of tools built off of the platform to give people a sense of what is possible. Most immediately this could just be OAM Docs & the OAM Uploader. Once it's built, we can use this space to highlight the PACiD tool.

At the bottom, we tie in a bit more of the indepth mission statement and point folks towards the contribution guidelines. This helps shape what our users are uploading, and frames it into the greater cause. We're already describing the tool up top and if people want to learn more they can go to the about page. 

I know it's important for users to be able to jump right into the tool and for these users they'll be able to because the tool will have it's own URL. Whether they are new or returning, users will be able to dive into the tool through a search engine or entering the URL in directly.

Overall I think this layout positions us pretty well for the immediate, but also future versions the project.

---

Now, this will be an additional lift, but this would be a pretty basic site along the lines of [sites](http://www.missingmaps.org/) [we've](http://devseed.com/openroads/) [already](http://docs.openaerialmap.org/) [built](http://electiondata.github.io/). Shouldn't be more than 3-4 eggrolls depending on revisions. 

& sitemap:

![artboard 1](https://cloud.githubusercontent.com/assets/9341928/16279387/c0a1a702-3888-11e6-8475-566192af18ea.jpg)

**Comment by smit1678** [comment]
@DylanMoriarty This is great. I like the thinking around the immediate plus future and having a landing page that can build that out. 

I have two comments of elements that we can figure out as it gets built but would be important to add in: 

  - Overall stats numbers. Number of images, km2 should be integrated somehow
  - Integrating overall stats or latest imagery into the initial view you see when you land. Something that shows you are already viewing the system and its activity. So instead of a placeholder image at the top, maybe something that is drawing from the system?

**Comment by DylanMoriarty** [comment]
Awesome.

It'd be really cool to set the top image as whatever the latest upload is, but I imagine that might be a bit difficult to pull off given the varying image sizes/shape/quality for a hero image. I can explore some options for integrating that though.

As for stats, that sounds good to me. I think stat's can be it's own section- the question here being what stats are we revealing/what would be most useful?

- Total number of images in the database
- # of images at km2

Are good candidates to start out. Would it be possible to highlight any of the following?

- # uploaded by users (as opposed to sat api's)
- # of different providers (sat api's + user count)
- # of different sensors

**Comment by cgiovando** [comment]
Thank you @DylanMoriarty and DevSeed team for these great ideas around the entry point strategy to OAM.

I think the main question that we need to answer is what do people come to OAM for and what do they expect to see? Probably until the user base reaches a threshold where most users are returning users and they just want to go straight to the map, then it would make sense to have this proposed landing page design at openaerialmap.org (while the map at openaerialmap.org/map or /browse).

As you mentioned it could resemble the Missing Maps website layout and include global content statistics. One thing that we may want to add to further engage and reward people for contributing imagery is in fact a "leaderboard" (in addition to the "latest image" section).

As the not-very-creative name indicates, OAM was inspired around 2007 by the OSM concept. The goal was to have a place to share all those images UAV images the same way that we were doing with GPS tracks for OSM. We envisioned that one day with all the crowdsourced imagery OAM would show a seamless mosaic covering the entire world. In that vision, anyone would go to OAM as they now go to OSM or Google Maps - **straight to the map** - to explore available imagery. Any metadata info about OAM would be in side links to about, contribute, docs, etc.

We're still far from the seamless mosaic, so 👍 on the proposed design, then we can easily move it to a secondary page when we think the map should be the main entry point instead.

**Comment by smit1678** [comment]
Sounds good @cgiovando, agreed. 

@DylanMoriarty @danielfdsilva Based on this idea, instead of having the browser load the map with a modal, we'll have the browser load a landing page first that will be at `http://beta.openaerialmap.org`. Then to access the map we'll go to `http://beta.openaerialmap.org/map/`. Correct? I think we then take off the `beta` subdomain once this is ready. Then the landing page and map are accessed at openaerialmap.org.

**Comment by smit1678** [comment]
Implemented and being tracked in the https://github.com/hotosm/openaerialmap.org repo.
