### ISSUE TITLE
OAM Statistics

### ISSUE THREAD

**Issue by DylanMoriarty** [hotosm/oam-browser#157]
Having statistics visible on the landing page are a good way to both show that the value of the system as well that it's active. 

Following the discussion from #154, we should figure out what stats are interesting and easily gathered.

Ideas so far include:
- # of images in the collection 
- # of different providers (sat api's + user count)
- # of contributors (can we track this without users?)

How many of these we choose to expose will help determine what a 'stats' section could look like for the landing page. Something simple:

<img width="530" alt="screenshot 2016-06-28 17 46 06" src="https://cloud.githubusercontent.com/assets/9341928/16433704/9cf32a8a-3d59-11e6-8e1c-6336340b0d22.png">

Or an explicit section for it,

<img width="505" alt="screenshot 2016-06-28 17 56 05" src="https://cloud.githubusercontent.com/assets/9341928/16433710/a0db948e-3d59-11e6-8ab4-53eea904fe81.png">

@danielfdsilva, @smit1678 any thoughts on the ideas so far or other potentially interesting things we could reveal?

**Comment by smit1678** [comment]
@DylanMoriarty To follow up here, I think the explicit section is good. Also change `users` to `providers` like you've done in the branch. 👍

**Comment by DylanMoriarty** [comment]
We settled on stats for the number of images, number of sensors, and number of providers. @nbumbarger did a awesome job building end points to fetch those as well.
