### ISSUE TITLE
Direct link to go back to OAM homepage?

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#162]
There's no direct way once you are in the OAM browser to click somewhere and go back to openaerialmap.org (the shortest path I found is through the about link from the info dropdown in the top right corner).

**Comment by DylanMoriarty** [comment]
You can get back by clicking on the logo, but that should be made more obvious. :+1:

**Comment by cgiovando** [comment]
Oh I didn't notice that :)

That may be enough then, or we could add another button near "Upload" that says "Home"?
