### ISSUE TITLE
Replace thumbnail preview with TMS

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#163]
Idea: when a TMS for an image is available, load the TMS on the map instead of the thumbnail (currently implemented). If no TMS available yet, just load the thumbnail. 

To consider:

  * If multiple TMS's associated with an image, which TMS is loaded?

My answer to the question would be to default to a TMS that was provided in the metadata when available, otherwise just take the first custom TMS if there are multiple. 

@danielfdsilva Anything else we should consider? Any other interaction or UX considerations here?

**Comment by danielfdsilva** [comment]
After trying to implement this we ran into a couple of problems.
Some of the tms, have either base map data, or black where no imagery is available.

![pasted image at 2016_08_26 11_44](https://cloud.githubusercontent.com/assets/1090606/18004947/f790f720-6b8e-11e6-83f7-86492dcbf794.png)

![screenshot from 2016-08-26 13 14 49](https://cloud.githubusercontent.com/assets/1090606/18004987/26cc65d8-6b8f-11e6-947c-56aea33b31ba.png)

This makes the whole previewing tms quite tricky as the experience is not great.
@DylanMoriarty @ricardomestre Ideas regarding a possible approach?

**Comment by danielfdsilva** [comment]
After some initial discussing with @ricardomestre the following option came up:

We leave the thumbnail as the default preview, and offer the user the option to preview the tms, or disable the preview altogether. We still have the problem with the strange tms s but since the user is freely choosing his options, it's on him.

Thoughts?

**Comment by smit1678** [comment]
@danielfdsilva That seems like a good plan. Where are you thinking of putting the toggle? Also raises the question -- is that something you want to implement for each TMS for an image? So if it has an original TMS plus a custom_tms, then can toggle both?
