### ISSUE TITLE
Base layer selection

### ISSUE THREAD

**Issue by danielfdsilva** [hotosm/oam-browser#175]
Implement an option to switch between some predefined base layers.

**Comment by danielfdsilva** [comment]
@smit1678 Could you you provide me with a list of base layers?
For each one, a name and the url is needed.

**Comment by smit1678** [comment]
I think the first three would be: 

- OpenStreetMap (current Mapbox layer)
- OpenStreetMap Standard
- Mapbox Satellite 

Do we want to include: 

- Bing? 
- Humanitarian Data Model? 

For future would be the OAM layer (not developed yet of course).

**Comment by danielfdsilva** [comment]
@smit1678 Can I get tile urls for those?

**Comment by smit1678** [comment]
- OSM Standard: `http://a.tile.openstreetmap.org/{z}/{x}/{y}.png`, [usage policy here](https://wiki.openstreetmap.org/wiki/Tile_usage_policy)
- Mapbox Satellite: `https://api.mapbox.com/styles/v1/hot/civicyccw00bv2io77zqq401h/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiaG90IiwiYSI6ImNpdmlkM2lkMDAwYTAydXBnNXFkd2EwemsifQ.KPrUb_mKlPmHCR6LNrSihQ`

**Comment by smit1678** [comment]
done via https://github.com/hotosm/oam-browser/pull/176
