### ISSUE TITLE
Pan map across date line

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#180]
May be some of a challenge with the complex grid calculations, but panning across the international dateline would be helpful. Especially in the Pacific and places like Fiji where islands are split across the date line. 

![oam-date-line](https://cloud.githubusercontent.com/assets/796838/20952731/526739a2-bc93-11e6-994a-cc1fbc79ae48.gif)

@danielfdsilva or others, thoughts on how we could solve this?

**Comment by danielfdsilva** [comment]
We could solve that part by removing the pan bounds. A trickier thing would be to draw the images across the dateline. Not sure how to do that from the top of my head. Should be doable, but we'd have to consider performance impact, if any.

**Comment by smit1678** [comment]
> We could solve that part by removing the pan bounds.

Can we test this and see how it feels? 

> A trickier thing would be to draw the images across the dateline.

You mean drawing the thumbnails across the dateline? I'm not sure how many potential images at the moment will be actually drawn across the dateline. Do you see trickiness with rendering the grid and making it selectable?

**Comment by danielfdsilva** [comment]
@smit1678 It's not trivial to render the features across the date line, because we're using coordinates to check wether a footprint falls in a cell, and after the date line the coordinate values don't match.

I've loosened the bound limits a bit in PR https://github.com/hotosm/oam-browser/pull/192. Could you check if this improves the experience?

**Comment by smit1678** [comment]
👍  Feels good and I think captures a good way to resolve this. 

We can revisit the features issue when it comes up but this isn't a problem right now.

**Comment by smit1678** [comment]
Implemented in https://github.com/hotosm/oam-browser/pull/192
