### ISSUE TITLE
Integrate how to get WMTS endpoints

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#189]
From https://github.com/hotosm/OpenAerialMap/issues/59, we will be enabling WMTS endpoints for all imagery processed through the Uploader. Right now we only expose the TMS endpoint through the dropdown selector and enable users to either open in an editor or copy to clipboard. 

I think we want to keep this interaction but add on some way to get the WMTS url and copy to clipboard. 

![](https://camo.githubusercontent.com/a7f9007eac78f08619e98f1375ca7479fc4a9bf1/68747470733a2f2f6170692e6d6f6e6f736e61702e636f6d2f7270632f66696c652f646f776e6c6f61643f69643d446b4b475476547a597537373650686166573565417948436275614c355a)

Ideas for how we can handle this?

**Comment by danielfdsilva** [comment]
Although technically simple, this poses some challenges UX/UI wise.
This would probably be another field with a url, right?

**Comment by smit1678** [comment]
Yeah, I guess the options are: 

Split the button: 

  - Copy to clipboard: TMS | WMTS

or 

Add another field: 

  - Copy TMS to clipboard
  - Copy WMTS to clipboard

Other ideas or options?

**Comment by danielfdsilva** [comment]
I assume the url is different right?
It's not good ux if we have a field with some text, and the when clicking copy, it copies something different (event if wmts is written). Those options are contextual of that field. Does this make sense?

**Comment by smit1678** [comment]
If I follow you correctly, the issue you're saying is that the dropdown is related the TMS which you can see partially in the element. If we add another item on the dropdown that even if we label it, it may not be clear to the user that they are copying something different? 

The urls are different but only slightly. These are the differences: 

`http://tiles.staging.openaerialmap.org/5885c3bb39240e00117b78c6/0/31d10d04-c626-4867-ba51-39deaf61337c/{z}/{x}/{y}.png`

`http://tiles.staging.openaerialmap.org/5885c3bb39240e00117b78c6/0/31d10d04-c626-4867-ba51-39deaf61337c/wmts`

**Comment by danielfdsilva** [comment]
Exactly!
I'd say we could add another field, but this would clutter the interface, or maybe remove the field and add a dropdown button for tms (with the existing options) and another one for wmts (only with copy).

**Comment by smit1678** [comment]
I feel like adding a second dropdown adds a lot of complexity when the two functions are very similar. 

What if we did this: 

* change the field text to be the main part of the URL which is the tilejson url: http://tiles.staging.openaerialmap.org/5885c3bb39240e00117b78c6/0/31d10d04-c626-4867-ba51-39deaf61337c
* Then have four dropdown actions: 
  - Open in iD
  - Open in JOSM
  - Copy TMS
  - Copy WMTS

**Comment by mojodna** [comment]
Yes, I like that, mainly because it triples as the TileJSON URL.

**Comment by mojodna** [comment]
So maybe "Copy TileJSON" as well? And add "URL" to each "Copy ..." entry?

**Comment by smit1678** [comment]
Made an attempt: 

![oam-dropdown](https://cloud.githubusercontent.com/assets/796838/22344694/fe90d6b0-e3f4-11e6-811b-f13bfb240fe7.gif)

**Comment by mojodna** [comment]
Works for me, in part because the full URL is usually not visible anyway.

**Comment by danielfdsilva** [comment]
After discussing this a bit with @ricardomestre adding the option under the dropdown with a small separator helps mitigate the issue. It's not a perfect solution but will do. Implemented in #196
