### ISSUE TITLE
Use HTTPS URL to open in JOSM

### ISSUE THREAD

**Issue by 13thirteen** [hotosm/oam-browser#202]
Currently the URL `http://127.0.0.1:8111` is used to open a result item with JOSM.
Since the OAM browser is now served under HTTPS, this leads to problems with some browsers that [block loading mixed active content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content).

Luckily, [JOSM is also listening for HTTPS on port 8112](https://josm.openstreetmap.de/wiki/Help/Preferences/RemoteControl).

Suggestion:
Handle this like the [OpenStreetMap website](https://github.com/openstreetmap/openstreetmap-website/blob/df17b997b33fc9d0c60360de7f27aadc76b930a0/app/assets/javascripts/index.js#L238-L240):
* If the website's protocol is `https` use URL `https://127.0.0.1:8112`
* Otherwise (protocol is `http`) use URL `http://127.0.0.1:8111`

**Comment by smit1678** [comment]
@13thirteen Thanks for looking at this and implementing a fix.

**Comment by smit1678** [comment]
Deployed on production.

**Comment by 13thirteen** [comment]
Great, thanks!
