### ISSUE TITLE
Add feedback confirmation

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#205]
When submitting feedback via the form there is no confirmation. Confirmation should be added to improve the user experience and help the user know that their submission was received.

**Comment by smit1678** [comment]
@tombh I pushed a fix to not have the `local.js` override `production.js`. It works [on staging](http://hotosm-oam-staging.s3-website-us-east-1.amazonaws.com/) and posts the feedback to the Google spreadsheet but it looks like it's still just showing an error response: 

![](https://api.monosnap.com/rpc/file/download?id=DDL3PlezVHpQjju6Dp6SvlZBMiWzNQ)

**Comment by tombh** [comment]
I see, the error in the console is to do with CORS:

`XMLHttpRequest cannot load https://docs.google.com/a/developmentseed.org/forms/d/1VOcERexikGP5N6xkjPDgUuDLUcS_Ktxj_ALNokNuttc/formResponse. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://hotosm-oam-staging.s3-website-us-east-1.amazonaws.com' is therefore not allowed access.`

So I think that error will only happen on staging? Google docs needs to accept requests from `http://hotosm-oam-staging.s3-website-us-east-1.amazonaws.com`.

Does that make sense?

**Comment by smit1678** [comment]
Yeah this CORS issue is a known issue (happens on production) because the current method is a workaround. Google Docs doesn't have the ability to specify acceptance of certain domains, correct @danielfdsilva?

**Comment by danielfdsilva** [comment]
@smit1678 @tombh Yes, there isn't a straightforward way to add data to a google form. The data is submitted but the response will always be an error.

**Comment by danielfdsilva** [comment]
@tombh That's also why I was using `.always()`. There's no way to get a success response. (Or I was never able to find one.)

**Comment by tombh** [comment]
Ha, well that's that then. No way to provide feedback to the user, if Google doesn't provide feedback.

Personally I think feedback forms are a bit old school anyway, a lot of effort, debugging, maintenance, etc (as we can see in this thread) for something that is equally achieved through multiple other channels.

It would be just as effective to have that feedback button popup a list of contact channels; email, twitter, etc.

**Comment by smit1678** [comment]
> Personally I think feedback forms are a bit old school anyway, a lot of effort, debugging, maintenance, etc (as we can see in this thread) for something that is equally achieved through multiple other channels.

At the heart of this work is capturing quick feedback reports in a workflow that does not require a user to open github (if they even have an account), or write an email in their email editor. It doesn't have to use Google Docs but as long as there is an easy method for a user to submit something. I'm open to other ideas: post directly to Github (may need to remove the email input) or post directly to Slack.

**Comment by tombh** [comment]
Well basically the best thing to do is create another API endpoint on `oam-catalog`. Hmm, but then strictly speaking we should have user auth then, otherwise the endpoint is open to abuse.

OMG, just did a little bit of research and found this! https://formspree.io/

It accepts POST HTTTP requests and forwards them to whatever is set for `your@email.com` :D 

```html
<form action="https://formspree.io/your@email.com"
      method="POST">
    <input type="text" name="name">
    <input type="email" name="_replyto">
    <input type="submit" value="Send">
</form>
```

What's the catch!?

**Comment by smit1678** [comment]
@tombh I've seen this before actually and this looks great. This may be easier to act upon and farm out to ticket or reply directly via email instead of having the data dumped into a spreadsheet. 

We can keep the same data inputs and layout we have right now right? Let's then just forward to `info@openaerialmap.org`.

**Comment by tombh** [comment]
Oh, the catch is that formspree.io redirects to a reCaptcha after submission :/ So to use this you are redirected away from the site :'(

**Comment by tombh** [comment]
I think the best solution then, is just to make our own endpoint on the catalog, or upload API for forwarding email. I guess the catalog API makes more sense?

**Comment by smit1678** [comment]
I think the Catalog probably makes more sense then it can become a feedback tracking endpoint. But do you think we switch to Formspree for now to start tracking it that way and then work this into any re-architecting?

**Comment by tombh** [comment]
Okay, I found another service similar to formspree, but doesn't force a captcha on you, it's: https://getsimpleform.com There should be a welcome email at the info@openaerialmap.org address. Trying it locally, I found the first form-sent email went into my spam, so you might have to go into your spam folder and mark it not spam to get future emails.
