### ISSUE TITLE
Map browser view doesn't show UI components

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#229]
When clicking on the View Image button from the Upload status form, the resulting map view does not include map UI components. 

Example: http://hotosm-oam-staging.s3-website-us-east-1.amazonaws.com/#/upload/status/59776885a7bcbc000c88feef?_k=d1qcmm

![oam-test](https://user-images.githubusercontent.com/796838/28584662-6cb42702-7165-11e7-8597-7c8e9df0e09c.gif)

**Comment by tombh** [comment]
This is already fixed in #228
