### ISSUE TITLE
Odd behavior where upload form resets to map view

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#230]
Odd behavior that I can't fully replicate, but seeing occasionally when on the upload form, it resets and clears out to so the map view.

Will try to find some ways to replicate better.

**Comment by tombh** [comment]
Yeah, we need something consistent to be able to fix this :/

**Comment by tombh** [comment]
Woohoo! Just figured this out. It was because the map's `moveend` event wasn't being unbound for non-map pages. This was probably a legacy from the merge with the uplaoder repo.

So this will be fixed in #230. I'll close it here now though.
