### ISSUE TITLE
Difference in styles

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#231]
Two differences in styles between current staging and production: 

1. Font in logo: 
  - ![openaerialmap uploader 2017-07-25 17-04-38-2](https://user-images.githubusercontent.com/796838/28584989-ad471f6c-7166-11e7-9e4a-9708319ecc2c.png)
2. Background color
  - ![openaerialmap uploader 2017-07-25 17-04-38](https://user-images.githubusercontent.com/796838/28585000-ba067446-7166-11e7-8df0-b5aaa1bd69ba.png)

**Comment by tombh** [comment]
Fixed in #228
