### ISSUE TITLE
Link View Image on Status page to image

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#240]
Current View Image link on Upload Status brings you to the user page view instead of the individual image view. Behavior should be to link directly to the image so the user can immediately see and view the details of the image uploaded. 

![openaerialmap browser 2017-10-01 08-14-19](https://user-images.githubusercontent.com/796838/31049135-d5e32e9e-a680-11e7-800b-37ca299bb807.png)

**Comment by tombh** [comment]
Fixed and deployed to staging

**Comment by cgiovando** [comment]
Not working probably because of #290
