### ISSUE TITLE
TMS not rendering on map

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#241]
This may be already on a todo but flagging that TMSs are not being rendered. Currently on browser, when selecting the Display as TMS button, the TMS for the image does not render on the map. 

*This is separate from the `OIN_BUCKET_PREFIX` issue on staging where we have it set as `558` and this breaks the dynamic tiler rendering*

No console errors and it seems that the tilesjson endpoint is called and returns successfully. 

![openaerialmap browser 2017-10-01 09-07-02](https://user-images.githubusercontent.com/796838/31049472-ebd71164-a687-11e7-9811-523521e4437f.png)

**Comment by smit1678** [comment]
See http://map-staging.openaerialmap.org/#/178.44406127929688,-18.132801356084773,11/latest/59cffa3291e41700d96b2a3c?_k=lr1ofj for example

**Comment by tombh** [comment]
This is fixed on staging, but only for new uploads.
