### ISSUE TITLE
The back button does not work as expected.

### ISSUE THREAD

**Issue by brendangatens** [hotosm/oam-browser#245]
In most cases, the back button isn’t available, but when it is, the behavior is unexpected.

https://www.dropbox.com/s/78b2ylhuhu60ifl/back-button-none.mov?dl=0
https://www.dropbox.com/s/djf7rwyy3d1p520/back-button-1.mov?dl=0

**Comment by tombh** [comment]
I suspect this is because of the use of React's `hashHistory` rather `browserHistory`. OAM uses the former because it's hosted on Github (which doesn't have the necessary server-side support for index.html routing). If OAM gets hosted on say S3 then the URLs could be moved over to `browserHistory`.
