### ISSUE TITLE
Split contents of main header

### ISSUE THREAD

**Issue by brendangatens** [hotosm/oam-browser#246]
Can we split up the contents of the .main-header so that the logo and the main-menu are contained in the sidebar, while the search bar, sign in options and profile nav are in a container that sits over the map?  Separating these will allow for more flexibility instead of requiring all items to be together in a fixed position.

**Comment by tombh** [comment]
Of course when you place the menu hamburger in the sidebar, it looks out of place on pages without the sidebar, such as the upload form. So I put this in a branch for you to play with: https://github.com/hotosm/oam-browser/commit/c1ea9bd6fba1bf081ba9cb1a48361bd360332e8a

**Comment by brendangatens** [comment]
Ah yes. Because we have the space when aren't in the map view, I'd prefer to make the full nav visible when we can. Maybe we could achieve this with CSS if we are able to add classes of `body-map` or `body-standard` to the body tag depending on if you're on a map view (or if the sidebar is present) or not?

<img width="1112" alt="screenshot 2017-10-06 08 27 40" src="https://user-images.githubusercontent.com/1270986/31267665-d8950128-aa70-11e7-9960-155bf4ac6428.png">

**Comment by brendangatens** [comment]
My preferred structure would be to better define elements inside the sidebar and in/on the map. At the moment, we have a fixed position page header that sits on top of both the sidebar and the map. It would make more sense, however, to keep a standard full-width header on non-map views. Because we won't have the sidebar in these views, we should be able to display the nav in full, rather than hiding it behind a drop down menu.

Below is how I would structure these. The elements with marked with a (*) are our main shared elements.

<img width="1109" alt="screenshot 2017-10-12 09 19 36" src="https://user-images.githubusercontent.com/1270986/31486317-00eb9566-af2f-11e7-863d-e7b84b1e09c6.png">
<img width="1110" alt="screenshot 2017-10-12 09 19 01" src="https://user-images.githubusercontent.com/1270986/31486322-04d53a74-af2f-11e7-8577-0069335f99df.png">


Map view

```
—— Sidebar
  —— Sidebar header
    —— Brand and main nav *
    —— Page headers
  —— Sidebar body
    —— Image filters
    —— Image results
  —— Sidebar footer
    —— Global footer *
—— Map container
  —— Map controls
  —— Account buttons and nav * (this might not need to live within the map container in the HTML, but visually this is where it lives. It could live outside of the container while being absolutely positioned to sit over the map)
  —— Map layer
```

Non-map view (Forms & Account)
```
—— Page header
  —— Brand and main nav *
  —— Account buttons and nav *
—— Page body
  —— Content
—— Global footer *
```
