### ISSUE TITLE
Load TMS by default

### ISSUE THREAD

**Issue by brendangatens** [hotosm/oam-browser#248]
To simplify the experience (and to create a quicker load) on a single image, can we load the TMS by default and take away the option to view the thumbnail on the map? Is there an advantage to viewing the the thumbnail in place of the TMS? We could add the ability to download the thumbnail image as a TIFF or PNG. On this topic, is thumbnail the correct term for this image?

**Comment by tombh** [comment]
This is fixed and deployed to staging.

I didn't remove the thumbnail option simply because I know there are currently images on production that don't have a TMS.
