### ISSUE TITLE
Hook up Dropbox and Google Drive uploading

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#249]

**Comment by tombh** [comment]
I've hooked up the relevant code for this and deployed to staging. But it seems that both Dropbox and Gdrive don't allow referrers from non-production URLs, so I can't fully test this yet. I've not used these services before, is it easy to setup staging versions?

**Comment by smit1678** [comment]
Great, will update for staging and test this out.

**Comment by smit1678** [comment]
Update: Dropbox referrer URL updated, tested, and it works. 

Google upload failed because we're missing the API key, https://github.com/hotosm/oam-catalog/blob/oauth-login/worker/process-image.js#L29. 

Next step, add google drive API key back into config.

**Comment by smit1678** [comment]
Added the API key as a variable in the config and it works, fix in https://github.com/hotosm/oam-catalog/pull/113
