### ISSUE TITLE
Side panel scroll under header

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#251]
@brendangatens I know this is on your list but is this related to #246? 

![openaerialmap browser 2017-10-05 17-25-32](https://user-images.githubusercontent.com/796838/31212284-c2c75f08-a9f3-11e7-8314-2fd2ea1c9cb1.png)

**Comment by brendangatens** [comment]
@smit1678 it is yup. Can't do much about this without splitting up the .main-header container. We could do some fakery to make this more natural by adding a white box behind logo that has equal width to do sidebar. I'll have a play.
