### ISSUE TITLE
Footer functionality not hooked up

### ISSUE THREAD

**Issue by brendangatens** [hotosm/oam-browser#258]
I've added some links to the footer on map views but need help with hooking up some of its functionality. The **feedback** button needs to open up its corresponding modal and the **status** color needs to connect with the status. At the moment there's a hard-coded green circle imitating an _up_ status.

This is in the [oath-login-footer-links](https://github.com/hotosm/oam-browser/tree/oath-login-footer-links) branch.

<img width="700" alt="screenshot 2017-10-16 09 24 57" src="https://user-images.githubusercontent.com/1270986/31603551-70768194-b258-11e7-9df1-ef43dcd8fc3e.png">

I'd probably like to see the footer made into its own component, placed inside the sidebar on a map view and across the bottom of the page on a non-map view. This would be part of the structure laid out here: https://github.com/hotosm/oam-browser/issues/246

**Comment by smit1678** [comment]
This was fixed in https://github.com/hotosm/oam-browser/commit/557339489220ea82548f4b59248950b3a069b8b6
