### ISSUE TITLE
TMS/WMTS doesn't work on some images

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#267]
The TMS/WMTS service doesn't work for this dataset: `https://map.openaerialmap.org/#/-72.23888397216797,18.614687921143883,11/square/032211203001/59e62be43d6412ef7220c2e5?_k=371x6y`

Trying to access from QGIS returns this error:

![screen shot 2017-10-24 at 12 25 44](https://user-images.githubusercontent.com/10201533/31924805-b55599b6-b849-11e7-8584-592626aa3d65.jpg)

Services for other images seem to work fine.

**Comment by smit1678** [comment]
@cgiovando I'm not reproducing the error in QGIS or in the browser. One issue with this image is that it looks like the minzoom is z13. So you need to zoom in to see it load. Are you using a specific version of QGIS? 

![qgis 2 18 13 2017-10-24 08-17-43](https://user-images.githubusercontent.com/796838/31948429-2b0dca76-b894-11e7-9151-609056a67fc2.png)
