### ISSUE TITLE
Open in JOSM is broken after site update

### ISSUE THREAD

**Issue by sergeyastakhov** [hotosm/oam-browser#268]
If you try to open in JOSM in new site, the error message is showed (tried in Chrome and Microsoft Edge).
The script is tries to parse a response from RemoteControl as json:

https://github.com/hotosm/oam-browser/blob/dc4687ce9e9ac69486685e543e4f2e39e7a8dad3/src/components/results_item.js#L132

But RemoteControl return as response is simple "OK", so exception is raised and error is shown.

**Comment by smit1678** [comment]
Tested and reproduced in both Chrome and Firefox. We'll need to dig into this some more and see where the issue is coming from. 

![openaerialmap browser 2017-11-15 11-15-21](https://user-images.githubusercontent.com/796838/32833582-377394ca-c9f7-11e7-996a-c3495525b059.png)
