### ISSUE TITLE
Upgrade to Mapbox GL

### ISSUE THREAD

**Issue by ricardoduplos** [hotosm/oam-browser#29]
Mapbox GL ftw?

**Comment by smit1678** [comment]
While we're not on Mapbox GL yet, we've switched to an updated Mapbox Light version plus added other base map layers with a switcher. Reopen if we want to revisit the default base map style.

**Comment by tombh** [comment]
What's the deal with the difference? The plain Mapbox JS version is missing a lot of the API methods from the Mapbox GL version, which seems much more feature-rich and maintained...

**Comment by smit1678** [comment]
Yeah I concur but I think we had started down the path of switching to Mapbox GL but scrapped it. I can't remember the reason nor find a ticket documenting the change cc @danielfdsilva?

**Comment by tombh** [comment]
Oh right, makes sense. Well anyway I'd certainly vote for the upgrade, but appreciate it's a biggy, so should be put on the long term lists.

**Comment by smit1678** [comment]
To reference, there is a `mapbox-gl` branch: https://github.com/hotosm/oam-browser/tree/feature/mapbox-gl

**Comment by danielfdsilva** [comment]
Changing to mapbox gl is definitely no easy task.
The main reason why we stopped was that mapbox gl doesn't support div markers, which we use to show the count of images per square, and we didn't find any suitable alternative back then.
I think creating the grid was also problematic, but I'm not sure about this one

**Comment by tombh** [comment]
Ah, that's a good reason. Well it's good to have this on record. Is this closed issue good enough for the records then? Maybe it should stay open, but just as long-term, non-urgent thing?

**Comment by smit1678** [comment]
Perhaps a separate new ticket since the gl refactor goes beyond just a base map style?

**Comment by tombh** [comment]
Or change the title here? The comments here will be useful for the future dev tackling this.
