### ISSUE TITLE
Point DNS to github repo

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#44]
@cgiovando Can you point the `beta.openaerialmap.org` subdomain to Github, similar to https://github.com/hotosm/openaerialmap.org/issues/3?

**Comment by cgiovando** [comment]
See if this works, otherwise re-open ticket with more instructions.

![screen shot 2015-05-26 at 15 24 38](https://cloud.githubusercontent.com/assets/10201533/7826168/49beb65e-03cb-11e5-9dd3-748ab07eb362.png)
