### ISSUE TITLE
Dropdowns

### ISSUE THREAD

**Issue by danielfdsilva** [hotosm/oam-browser#53]
- [x] Implement dropdown system

Implement tms usage options:
- [x] Use with iD
- [x] Use with JOSM
- [x] Copy to clipboard

**Comment by smit1678** [comment]
See HOT Tasking Manager for similar implementation of use with iD and JOSM: http://tasks.hotosm.org/

**Comment by anandthakker** [comment]
Specifically: https://github.com/hotosm/osm-tasking-manager2/blob/0b67c5d2b2fde088319a777168827033fcb73dbe/osmtm/static/js/project.js#L345-L495

**Comment by anandthakker** [comment]
Closed in #89
