### ISSUE TITLE
Automatically switch to footprint display when fewer images in map area

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#57]
When only few images are displayed in the map area (at any zoom level), the display could automatically switch from tiles/cells to image footprints. This would normally happen when zooming in to a smaller area or by limiting the number of images displayed through a filter.

**Comment by smit1678** [comment]
@cgiovando Let's push this to a future version as v2 is still focused core functionality.

**Comment by smit1678** [comment]
Closing this in preference to #56. Use that ticket for capturing the goal of showing an alternative way of viewing imagery in an area instead of just the grid.
