### ISSUE TITLE
Allow selecting images to send for processing by OAM Server

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#58]
If displaying original OIN images and no tile service is available, the authenticated user should be able to select those images of interest and submit for processing by the OAM Server. The produced TMS will then be added to the OAM catalog for display and use through the OAM browser.

This workflow should be defined by specific API functions and coordinated with OAM Server developers.

**Comment by smit1678** [comment]
All uploaded imagery through OAM gets a TMS now through the dynamic tiler. Need to reopen a new ticket with new framing if we want to consider ways to create custom mosaics in the future.
