### ISSUE TITLE
Remove filling from selected squares

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#59]
Once the user selects a square (on click) the style should switch from solid color to just outline. This allows to see footprints and background map better. The edge of selected squares could be made ticker to indicate the current selection.

**Comment by smit1678** [comment]
@cgiovando The outline of the selected square may potentially be confused with the outline of the footprints. We can take a look at the opacity of the selected color to see where improvements can be made.

**Comment by cgiovando** [comment]
How about just using different colors and thickness for image footprints and grid lines?
