### ISSUE TITLE
Display image previews on map

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#60]
Each image preview (or the actual TMS layer where available) could be displayed directly on the map inside each footprint. This could be a switch in the control sidebar that turns all image previews in map on, or would be triggered by clicking on each footprint on the map

**Comment by smit1678** [comment]
Thumbnail displayed on map within the footprint once a user clicks on an image. Implemented by https://github.com/hotosm/oam-browser/commit/d6bd521c0d6d83b7d82ad12e9607e4d903546b27
