### ISSUE TITLE
Density grid is not shown on zoom <= 5

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#67]
When zoomed out to zoom level 5 or lower the *density grid* layer disappears.

**Comment by smit1678** [comment]
This is due to performance reasons. Related to #77 and #78. We should look to limit zooming out to provide a better user experience here.

**Comment by smit1678** [comment]
Resolved by https://github.com/hotosm/oam-browser/pull/81 & https://github.com/hotosm/oam-browser/pull/82. We're limiting zooming out and implemented a mini map to improve performance and enable quick jumps around the globe.
