### ISSUE TITLE
Add ZYX to map URL

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#68]
Something like osm.org for easily sharing and referencing a map view:

http://beta.openaerialmap.org/#map=7/-15.385/35.574

**Comment by cgiovando** [comment]
I don't see this in http://beta.openaerialmap.org

Has it not been deployed yet?

**Comment by smit1678** [comment]
Nope not live yet, in the develop branch and will be a part of the v2 release.

**Comment by cgiovando** [comment]
Cool - is there a deployed version of the dev branch?
