### ISSUE TITLE
Display full metadata information

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#7]
Display full metadata information available.

**Comment by ricardomestre** [comment]
- [ ] Download size
- [ ] Provider
- [ ] ...

**Comment by cgiovando** [comment]
Extended metadata could be displayed with a click panel open/close at the bottom of the current basic metadata area and sourced directly from OIN/OAM metadata schemas.

**Comment by anandthakker** [comment]
Closed by #96
