### ISSUE TITLE
Result type = "Service", "Image" or "Service + Image"

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#74]
Instead of current options "Multiscene TMS" and "Single Scene", I would suggest using:

- **Service** for when a tile service is available (or [specific tile schema per OAM Server](https://github.com/hotosm/oam-server/issues/5))  
- **Image** for when a single file is returned from OIN (it can be a single scene or a mosaic/strip)  
- **Service + Image** for when both of the above are available (image download from OIN and tile service from OAM)  

When only the *image* is available, (authenticated?) OAM users should be allowed to click on "*create service*" button, which triggers the tile service creation job in OAM Server. Once the tile service creation is complete, that same result will then be a *Service + Image* type.

Multiple results of type *Image* could be selected by the user to mosaic into a tile service creation job request (see #73). All those results will then be *Service + Image* type.

**Comment by smit1678** [comment]
@cgiovando Do we expect to have only Tile Services without raw image downloads? Right now we're only indexing images available in OIN. I suggest we only use **Image** and **Service + Image**.

**Comment by cgiovando** [comment]
Agree @smit1678 - we will later investigate the case of tile service only. Keeping track [here](https://github.com/hotosm/oam-server/issues/6) and in #85

**Comment by smit1678** [comment]
Coming back on the language here. Service is too vague. Proposing to use: `Image + Tiled Map` and `Image`

**Comment by cgiovando** [comment]
`Tiled Map` is also not obvious to someone who doesn't know about tile map services. I would propose `Map Service` and `Image`.

If agreed, please reflect in #80 as well.

**Comment by smit1678** [comment]
@cgiovando Map Service still seems a little too vague. What about going back to `Tile Service`? Or we could do `Web Map`?

**Comment by cgiovando** [comment]
Actually `Map Service` is the common part of `Web Map Service (WMS)` and `Tile Map Service (TMS)`. Since [we haven't decided yet](https://github.com/hotosm/oam-server/issues/5) what service will OAM Server output by default, I would not worry about it now and go with either one. If you think `Tile Service` is most obvious, then let's go with it.

**Comment by anandthakker** [comment]
Closed by #86
