### ISSUE TITLE
Mini map for quick navigation

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#78]
A mini map may be useful for quick navigation. @ricardomestre where do you see this best positioned on the page?

**Comment by danielfdsilva** [comment]
the minimap should also show the location of the selected square (if any)

**Comment by smit1678** [comment]
@danielfdsilva Are you thinking something like showing the area of the world you're viewing plus the location of the selected square? 

![astro digital browser 2015-06-11 12-03-58](https://cloud.githubusercontent.com/assets/796838/8111864/2ee13d7a-1032-11e5-9bec-ca1b3447a4d3.png)

**Comment by danielfdsilva** [comment]
Precisely, not sure what's the best to use, if marker or something else. @ricardomestre suggestions?

**Comment by kamicut** [comment]
@danielfdsilva @ricardomestre wouldn't that duplicate the UI? The point of the minimap is to enhance navigation, it should be restricted to that.

**Comment by danielfdsilva** [comment]
Imagine you're zoomed somewhere and you want to go back to the selected square. Having some indication in the mini map allows you to do that.
We don't need to show the selected sqaure, just a marker or something.
