### ISSUE TITLE
Sorting for panel

### ISSUE THREAD

**Issue by kamicut** [hotosm/oam-browser#79]
Filtering (#27) will give specific results. If there are no filters set, we might need to sort the panel as well by resolution/date "score" to create a "best image available" list.

Thoughts?

**Comment by cgiovando** [comment]
I would say default sorting goes with best resolution and most recent dates on top. We may be able to build an automatic "score" based on the number of times an images has been downloaded (e.g. sorted by most popular).

**Comment by smit1678** [comment]
Solving by default sorting within the API - showing higher resolution and newer imagery first: https://github.com/hotosm/oam-catalog/commit/c0e6e473ae3810638fca29419408dd5ae17a7a02. Closing this out for now, can pick up further improvements in new tickets.
