### ISSUE TITLE
Nominatim instead of Mapbox geocoder

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#84]
It looks like the current place search box is powered by Mapbox geocoding service, which according to this [page](https://www.mapbox.com/developers/api/geocoding/) requires a Mapbox plan subscription.

Can we achieve the same functionalities with [Nominatim]( http://wiki.openstreetmap.org/wiki/Nominatim)?

**Comment by cgiovando** [comment]
Related to #51

**Comment by smit1678** [comment]
We can look at this. HOT also has a Mapbox account that we'll want to switch to anyways. Right now we're just using a dev Devseed account.

**Comment by cgiovando** [comment]
Cool - do you know who's the contact person for that account? If it's @wonderchook I'll coordinate with her to migrate to HOT's sysadmin.

I think it would still be good to have the option of nominatim, especially for the packaged version so that anyone installing OAM is not tied to having a Mapbox account.

Maybe both and one can decide?

**Comment by anandthakker** [comment]
Since we're using `mapbox.js` and layers hosted on Mapbox for the map, there's already a Mapbox dependency that goes deeper than just geocoder.  (Also, we're using the `mapbox.places` level of the geocoder API, which is free with any Mapbox plan.)
