### ISSUE TITLE
Tile/map services without OIN sources?

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#85]
Shall OAM index tile and map services from third parties in addition to those created from OIN sources and published by the OAM Server? See also #74 and [this](https://github.com/hotosm/oam-server/issues/6)

**Comment by smit1678** [comment]
Not sure if providing tile services without OIN sources is on the near term. I agree with @mojodna and feel like this is outside the roll of OAM at the moment.

**Comment by smit1678** [comment]
Closing this. Additional convo should happen in https://github.com/hotosm/OpenAerialMap/issues/45
