### ISSUE TITLE
Unable to pan in browser after panning across international date line

### ISSUE THREAD

**Issue by SteveBower** [hotosm/oam-browser#99]
Panning across the international data line (roughly), at some zoom levels, causes the “Loading” indicator to appear and remain spinning, and the user can no longer pan. This only seems to happen at certain zoom levels. The user must refresh the browser and start over.

To reproduce: Open the browser and search for “vanuatu”. Pan to the east, try to center Fiji on the monitor. After 2 or 3 tries the “Loading” indicator appears. You may be able to pan 1 or 2 more times, after which you can no longer pan. If this doesn’t reproduce the issue, try it at a couple other zoom levels. I could only reproduce at the “vanuatu” level, and zoomed out once.

Chrome 43.0.2357.130 on Win 7 Pro.

Presumably a low priority - but seemed worth capturing the issue.

**Comment by danielfdsilva** [comment]
Fixed with the new grid system
